### ISSUE TITLE
GitHub releases are outdated

### ISSUE THREAD

**Issue by Marcono1234** [OpenHFT/Java-Runtime-Compiler#117]
The GitHub releases tab (https://github.com/OpenHFT/Java-Runtime-Compiler/releases) is outdated. It still lists compiler-2.21ea80 from 2021 as latest release.

Could you please create new GitHub release entries for the versions you have released in between?
Or, in case you are not planning to update the GitHub releases anymore, you could hide them by clicking the gear icon next to the "About" section on the right side of your repository view; this would then reduce confusion about what the latest release is.

**Comment by alamar** [comment]
Done!
