### ISSUE TITLE
solving tools.jar dependency in chroniclemap lib while migrating to JRE 11 

### ISSUE THREAD

**Issue by kannankalli** [OpenHFT/Java-Runtime-Compiler#129]
HI, 
We are migrating our application to JRE 11 from JRE 8. we are using 3.23.5 version of chronicle map. Application is shutting down while starting. Below is the error 

Exception in thread "main" java.lang.AssertionError: java.lang.ClassNotFoundException: com.sun.tools.javac.api.JavacTool
at net.openhft.compiler.CompilerUtils.reset(CompilerUtils.java:64)

Based on my understanding, tools.jar is not present any more in jre 11.  But chorincle map depends on JAvacTool which is from tools.jar. How should we mitigate this problem ? 
Should i add tools.jar as part of the classpath in JRE 11  ( copied from JRE 8 ) ?

**Comment by tgd** [comment]
Hi @kannankalli - we have working CI builds for Chronicle Map and Java Runtime Compiler on Java 11. Can you share with us some sample code that will reproduce the issue please?

If you need expedited commercial support please contact us here: https://chronicle.software/contact-us/

**Comment by tgd** [comment]
Hi @kannankalli closing out this issue as we haven't heard back for some time. If its still an issue for you please re-open. If you would like to expedite the development of this please get in touch with us here for commercial support: https://chronicle.software/contact-us/
