### ISSUE TITLE
Getting the " package does not exist" exception while loading with custom class loader

### ISSUE THREAD

**Issue by SaeedMasoumi** [OpenHFT/Java-Runtime-Compiler#13]
I have a `URLClassLoader ` which i added my jar file dependency to it . The below example throw `package com.mypackage does not exist` exception
```
 String className = "mypackage.MyClass";
        String javaCode = "package mypackage;\n" +
                "public class MyClass implements Runnable {\n" +
                "private com.mypackage.MyClass clazz;\n" +
                "    public void run() {\n" +
                "        System.out.println(\"Hello World\");\n" +
                "    }\n" +
                "}\n";
        println project.buildDir
        Class aClass =  CompilerUtils.CACHED_COMPILER.loadFromJava(classLoader, className, javaCode);
        Runnable runner = (Runnable) aClass.newInstance();
        runner.run();
```
But `Class.forName("com.mypackage.MyClass",true,classLoader)` returns the class object of `MyClass`.

**Comment by leventov** [comment]
Are you sure you don't confuse `"com.mypackage.MyClass"` and `"mypackage.MyClass"`?

Either way note that this project is probably not supported anymore.

**Comment by SaeedMasoumi** [comment]
Oh, I was wrong. I forgot to add my jar to the classpath with `CompilerUtils.addClassPath`
