### ISSUE TITLE
Inconsistent license information

### ISSUE THREAD

**Issue by ebourg** [OpenHFT/Java-Runtime-Compiler#14]
Hi,

The LICENSE file was switched to LGPL-3 but the headers in the .java files still refer to the Apache-2.0 license. The headers should be updated, or the LICENSE file switched back to Apache-2.0 (which may be a good idea considering that Apache projects are [not allowed](http://www.apache.org/legal/resolved.html#category-x) to use LGPL libraries).

**Comment by peter-lawrey** [comment]
Thank you for picking that up. It should be Apache 2.0 now.
