### ISSUE TITLE
Allow injection of PrintStreams instead of outputting to System.out/err

### ISSUE THREAD

**Issue by renatoathaydes** [OpenHFT/Java-Runtime-Compiler#16]
I want to use the compiler in my application, but I don't want the output to go to stdout and stderr.

Is it possible to add a setter somewhere so we can control where the output of the compiler ends up?

**Comment by leventov** [comment]
Could you please provide a pull request?

**Comment by renatoathaydes** [comment]
I wouldn't mind, but this library is not documented, which makes it hard to contribute (as to know what may be affected by my changes my only source of information is the *source code*).

If you added just the public API you expect to be used to the README page, that would be really helpful.

Looking at the source, it seems it's not this library printing out errors to sysout, I believe is the JavaTool compiler class that does it... but that class probably lets you set a PrintStream or something like that... I will check that out.

**Comment by leventov** [comment]
As the scope of the change is adding ability to configure printing out, existing users shouldn't be affected by such a change.

This library is in the community support mode so I or @peter-lawrey are keen to accept any PR that looks reasonable. Feel free to use your judgement regarding API design.

**Comment by peter-lawrey** [comment]
Agreed. As long as existing users would not be impacted we would be happy
to take a PR.
