### ISSUE TITLE
Source files without license headers - invalid license file

### ISSUE THREAD

**Issue by puntogil** [OpenHFT/Java-Runtime-Compiler#20]
Hi
The following source files are without license headers.

./compiler/src/test/java/eg/FooBarTee.java

Please, confirm the licensing of code and/or content/s, and add license headers.

https://fedoraproject.org/wiki/Packaging:LicensingGuidelines?rd=Packaging/LicensingGuidelines#License_Clarification

LICENSE.adoc file, usually it is considered as the "NOTICE" file used in projects of this type of license. You could use this instead http://www.apache.org/licenses/LICENSE-2.0.txt ?

Thanks in advance
Regards

**Comment by peter-lawrey** [comment]
Thank you for finding that class.

I have included the full LICENSE details at the top level.
