### ISSUE TITLE
Java Runtime Compiler with Wilfly Swarm 

### ISSUE THREAD

**Issue by rac021** [OpenHFT/Java-Runtime-Compiler#24]
Hi, 

I'm using java runtime compiler in a wildfly swarm project.

When I'm on my IDE, everything works fine, but after building my jar and deploying my app,
I'm have compilation errors that says that some class does not exists ( knowing that this classes ar in the jar app )

Anyone to tells me what's wrong ?

Thank's 

R

**Comment by RobAustin** [comment]
@rac021  closing as this is a question rather than an issue
