### ISSUE TITLE
How to handle stale cache issues

### ISSUE THREAD

**Issue by vittali** [OpenHFT/Java-Runtime-Compiler#29]
This is more a question than an issue. If I understand the code correctly, the purpose of caching is
to avoid compiling the same class twice. But if the source code changes, recompiling should probably take place. So the question is: shouldn't there be some mechanism to auto-recompile in case of source code changes ( perhaps with some hash like md5 or with timestamps ) or at least a method to clear the entire cache ? Or do I miss something ?

**Comment by peter-lawrey** [comment]
The reason for caching is to allow you to have classes which depend on each
other. say you compile A and later compile B which uses A.

Note: the JVM doesn't allow you to load a class more than once, with the
same or different byte code.

What you can do is either use Instrumentation to change a class (with
significant limitations) or load the class into a different ClassLoader.

If a class might change each time you compile some code. I suggest using a
different ClassLoader each time.
ᐧ

**Comment by vittali** [comment]
Thank you, that was very helpful.
