### ISSUE TITLE
reCompile question

### ISSUE THREAD

**Issue by XShandow** [OpenHFT/Java-Runtime-Compiler#30]
when I compile a java file,the second time cannot work,it is  still the first one.(I will change the code,but will not change the classname)How can make it diffierent when I compile it.
give me help ,3Q.

**Comment by dpisklov** [comment]
From what I could decode, this is not a question about org.openhft compiler but rather Java compiler.
Regardless, for questions, there's stackoverflow. Github is for real issues.
