### ISSUE TITLE
Illegal reflective access operation (java 10)

### ISSUE THREAD

**Issue by vittali** [OpenHFT/Java-Runtime-Compiler#34]
Issue 33 didn't fix the problem for me:

WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by net.openhft.compiler.CompilerUtils (file:/home/p/.gradle/caches/modules-2/files-2.1/net.openhft/compiler/2.3.1/1
c598d9164a3bc8f163c19ca750c3a09a69c52af/compiler-2.3.1.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int)
WARNING: Please consider reporting this to the maintainers of net.openhft.compiler.CompilerUtils
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release

**Comment by RobAustin** [comment]
relates to #33

**Comment by RobAustin** [comment]
@vittali I see the code is generating WARNINGs but are you saying it does not work, or that you want the WARNINGs removed. If the code is not working can you send the exception.
