### ISSUE TITLE
I got ClassNotFoundException in Linux

### ISSUE THREAD

**Issue by ZhaoxuanSu** [OpenHFT/Java-Runtime-Compiler#35]
It runs well in Eclipse IDE in WINDOWS. But I got ClassNotFoundException when running it in Linux. This project is building by SpringBoot and packing by Maven with JDK1.8.0_112.

Exception detail: 
Caused by: java.lang.ClassNotFoundException: com.szx.core.logexp.dc.Lecilfaafaafroolfaafaafr
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at org.springframework.boot.loader.LaunchedURLClassLoader.loadClass(LaunchedURLClassLoader.java:94)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at net.openhft.compiler.CachedCompiler.loadFromJava(CachedCompiler.java:163)
	at net.openhft.compiler.CachedCompiler.loadFromJava(CachedCompiler.java:70)

My code:
 CompilerUtils.CACHED_COMPILER.loadFromJava(className, javaCode).newInstance();

So what problem did I got?

**Comment by dpisklov** [comment]
Can you show the full code? Likely you have inconsistency between class name and class code

**Comment by ZhaoxuanSu** [comment]
> Can you show the full code? Likely you have inconsistency between class name and class code

Here's the full code:

package com.szx.core.logexp.impl;

import java.util.UUID;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import com.szx.core.logexp.LogicalExpression;
import com.szx.core.logexp.LogicalExpressionException;
import com.szx.core.logexp.LogicalExpressionUtils;

import net.openhft.compiler.CompilerUtils;

public class DynamicCompilingLogicalExpression implements LogicalExpression {

	private static final Logger logger = LoggerFactory.getLogger(DynamicCompilingLogicalExpression.class);

	private static final int ID_THRESHOLD = 1 << 10;// 1024

	private static final String CLASS_NAME = "com.szx.core.logexp.dc.Leci${ID}";
	private static final String JAVA_CODE = "package com.szx.core.logexp.dc;"
			+ "import com.szx.core.logexp.impl.DynamicCompilingLogicalExpression.LogicalExpressionCompiler;"
			+ "public class Leci${ID} implements LogicalExpressionCompiler {public boolean test(){return ${expression};}}";

	@Override
	public boolean test(String expression) throws LogicalExpressionException {
		String id = getId(expression);
		String className = CLASS_NAME.replace("${ID}", id);
		String javaCode = JAVA_CODE.replace("${ID}", id).replace("${expression}", expression);
		logger.debug("expression : {} , java code to be compiled : {}", expression, javaCode);
		try {
			return ((LogicalExpressionCompiler) CompilerUtils.CACHED_COMPILER.loadFromJava(className, javaCode).newInstance()).test();
		} catch (Exception e) {
			throw new LogicalExpressionException(e);
		}
	}

	private String getId(String expression) {
		String simpleAlphabet = LogicalExpressionUtils.toSimpleAlphabet(expression);
		return simpleAlphabet.length() >= ID_THRESHOLD
				? UUID.randomUUID().toString().replaceAll("-", "")
				: simpleAlphabet;
	}

	public static interface LogicalExpressionCompiler {

		boolean test();

	}

}

**Comment by dpisklov** [comment]
What expression are you using for your test? Most likely that expression is not compilable, and just before the error "Caused by: java.lang.ClassNotFoundException: com.szx.core.logexp.dc.Lecilfaafaafroolfaafaafr" you can see (in my example the expression is different proobably but still)"
```
public class Lecialskdj implements LogicalExpressionCompiler {public boolean test(){return alskdj;}}
                                                                                           ^
  symbol:   variable alskdj
  location: class com.szx.core.logexp.dc.Lecialskdj
```

**Comment by ZhaoxuanSu** [comment]
I use it to test a logical expression like this:

The test class:
------------------------------------------------
package com.szx.core.logexp;

public class Test {

	public static void main(String[] args) {
		try {
			LogicalExpression le = LogicalExpression.getInstance();
			boolean test = le.test("true&&true");
			System.out.println(test);
		} catch (LogicalExpressionException e) {
			e.printStackTrace();
		}
	}

}



All other related classes:
------------------------------------------------
package com.szx.core.logexp;

import com.szx.core.logexp.impl.DynamicCompilingLogicalExpression;

public interface LogicalExpression {

	public static LogicalExpression getInstance() {
		return new DynamicCompilingLogicalExpression();
	}

	boolean test(String expression) throws LogicalExpressionException;

}
------------------------------------------------
package com.szx.core.logexp;

public class LogicalExpressionUtils {

	private LogicalExpressionUtils() {

	}

	public static String toSimpleAlphabet(String expression) {
		return expression.replaceAll("true", "t").replaceAll("false", "f")
				.replaceAll("!", "n").replaceAll("&", "a").replaceAll("\\|", "o")
				.replaceAll("\\(", "l").replaceAll("\\)", "r");
	}

}
------------------------------------------------
package com.szx.core.logexp;

public class LogicalExpressionException extends Exception {

	private static final long serialVersionUID = -8160132685836211934L;

	public LogicalExpressionException(String message) {
		super(message);
	}

	public LogicalExpressionException(String message, Throwable cause) {
		super(message, cause);
	}

	public LogicalExpressionException(Throwable cause) {
		super(cause);
	}

}

**Comment by dpisklov** [comment]
I stripped down your code slightly into a JUnit test case, and it works fine. I'm not sure why you see the issue.
Try my code below and see if it  works for you:
```
package eg;

import net.openhft.compiler.CompilerUtils;
import org.junit.Test;

import java.util.UUID;

public class TestCompile {
    private static final int ID_THRESHOLD = 1 << 10;// 1024

    private static final String CLASS_NAME = "com.szx.core.logexp.dc.Leci${ID}";
    private static final String JAVA_CODE = "package com.szx.core.logexp.dc;\n"
            + "import eg.TestCompile.LogicalExpressionCompiler;\n"
            + "public class Leci${ID} implements LogicalExpressionCompiler {public boolean test(){return ${expression};}}\n";

    public boolean test(String expression) {
        String id = getId(expression);
        String className = CLASS_NAME.replace("${ID}", id);
        String javaCode = JAVA_CODE.replace("${ID}", id).replace("${expression}", expression);
        System.out.println("expression : " + expression + " , java code to be compiled : " + javaCode);
        try {
            return ((LogicalExpressionCompiler) CompilerUtils.CACHED_COMPILER.loadFromJava(className, javaCode).newInstance()).test();
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }

    private String getId(String expression) {
        String simpleAlphabet = toSimpleAlphabet(expression);
        return simpleAlphabet.length() >= ID_THRESHOLD
                ? UUID.randomUUID().toString().replaceAll("-", "")
                : simpleAlphabet;
    }

    public static String toSimpleAlphabet(String expression) {
        return expression.replaceAll("true", "t").replaceAll("false", "f")
                .replaceAll("!", "n").replaceAll("&", "a").replaceAll("\\|", "o")
                .replaceAll("\\(", "l").replaceAll("\\)", "r");
    }

    public static interface LogicalExpressionCompiler {
        boolean test();
    }

    @Test
    public void testCompile() {
        test("true&&true");
    }
}

```

**Comment by dpisklov** [comment]
Closing due to lack of response

**Comment by radiantgurl** [comment]
i have the same issue
