### ISSUE TITLE
Get the stack trace 

### ISSUE THREAD

**Issue by Meshredded** [OpenHFT/Java-Runtime-Compiler#39]
Hi,
I'd like to capture the stack trace when the compilation fails right now i got the following console output when compilation fails :
```
/org/javascool/JvsToJavaTranslated2.java:5: error: invalid method declaration; return type required
int toot(){
    ^
```
Is it possible to capture this output in a String ?
Thank you.

**Comment by RobAustin** [comment]
@Meshredded can you provide some sample code to allow me to reproduce this issue, I will then be able to better advise you on how you can obtain the string output you are looking for.

**Comment by JerryShea** [comment]
Closing as here has not been a response. @Meshredded please re-open if you have some more information
