### ISSUE TITLE
NullPointerException suspect at s_standardJavaFileManager

### ISSUE THREAD

**Issue by Rednoll** [OpenHFT/Java-Runtime-Compiler#41]
Creating compiler:
	
```
public static CachedCompiler compiler = null;
	
static {
		
	File srcDir = new File("compiler/src");
	srcDir.mkdirs();
		
	File binDir = new File("compiler/bin");
	binDir.mkdirs();
		
	compiler = new CachedCompiler(srcDir, binDir);
}
```

Stack trace part:
Exception in thread "main" java.lang.NullPointerException
	at net.openhft.compiler.CachedCompiler.compileFromJava(CachedCompiler.java:94)
	at net.openhft.compiler.CachedCompiler.loadFromJava(CachedCompiler.java:143)
	at net.openhft.compiler.CachedCompiler.loadFromJava(CachedCompiler.java:70)

**Comment by belkirdi** [comment]
I have the same issue. Not able to attach the source code on debug mode

**Comment by belkirdi** [comment]
aClass.newInstance();
This function on the class is deprecated from JAVA 8 you should use  : 
aClass.getConstructor().newInstance();

**Comment by Rednoll** [comment]
> I have the same issue. Not able to attach the source code on debug mode using (OpenJDK 11)
> 
> WARNING: An illegal reflective access operation has occurred
> WARNING: Illegal reflective access by net.openhft.compiler.MyJavaFileManager (file:/home/xxx/.m2/repository/net/openhft/compiler/2.3.4/compiler-2.3.4.jar) to method com.sun.tools.javac.file.JavacFileManager.listLocationsForModules(javax.tools.JavaFileManager$Location)
> WARNING: Please consider reporting this to the maintainers of net.openhft.compiler.MyJavaFileManager
> WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
> WARNING: All illegal access operations will be denied in a future release


I found a sy

**Comment by Rednoll** [comment]
I found a stub:

```
public static CachedCompiler compiler = null;
	
static {	
	File binDir = new File("compiler/bin");
	binDir.mkdirs();
		
	compiler = new CachedCompiler(null, binDir);
}
```

**Comment by JerryShea** [comment]
I believe that this should work with Javas 8, 11 and 17. Closing, but please re-open if you can reproduce this problem
