### ISSUE TITLE
Java 12/13/...

### ISSUE THREAD

**Issue by Allsimon** [OpenHFT/Java-Runtime-Compiler#43]
Hello,

Is there any plan to support Java 12 ? 
If not, do you know any viable replacement to migrate to ?

**Comment by belkirdi** [comment]
Same question here

**Comment by dpisklov** [comment]
@belkirdi @Allsimon Chronicle's support policy is to support LTS releases.
So far, LTS releases are Java 8 and Java 11. Next LTS release is Java 17. We don't plan to support versions in between 11 and 17 (except for paid clients).

HTH

**Comment by belkirdi** [comment]
@dpisklov Thanks for your clarification
