### ISSUE TITLE
Java 14 : CachedCompiler.loadFromJava() throws java.lang.NoSuchFieldException: override

### ISSUE THREAD

**Issue by saulpalv** [OpenHFT/Java-Runtime-Compiler#48]
Code Works Well On JDK 11 but crashes on JDK 11
Im using LibericaJDK

Exception in thread "main" java.lang.AssertionError: java.lang.NoSuchFieldException: override
	at net.openhft.compiler.CompilerUtils.<clinit>(CompilerUtils.java:64)
	at net.openhft.compiler.CachedCompiler.loadFromJava(CachedCompiler.java:140)
	at net.openhft.compiler.CachedCompiler.loadFromJava(CachedCompiler.java:76)
	at Test.DynamicJavaClassLoading.getStrategy(DynamicJavaClassLoading.java:51)
	at Test.DynamicJavaClassLoading.main(DynamicJavaClassLoading.java:34)
Caused by: java.lang.NoSuchFieldException: override
	at java.base/java.lang.Class.getDeclaredField(Class.java:2489)
	at net.openhft.compiler.CompilerUtils.<clinit>(CompilerUtils.java:60)
	... 4 more

`package Test;

import net.openhft.compiler.CachedCompiler;

import java.lang.reflect.InvocationTargetException;

/**
 * Loads the addingStrategy and then after 3s replaces it with the
 * subtractingStrategy.
 */
public class DynamicJavaClassLoading {

    private final static String className = "Test.MyClass";
    private final static String addingStrategy = "package Test;\n" +
            "import Test.DynamicJavaClassLoading.Strategy;\n" +
            "public class MyClass implements Strategy {\n" +
            "    public int compute(int a, int b) {\n" +
            "        return a+b;\n" +
            "    }\n" +
            "}\n";

    private final static String subtractingStrategy = "package Test;\n" +
            "import Test.DynamicJavaClassLoading.Strategy;\n" +
            "public class MyClass implements Strategy {\n" +
            "    public int compute(int a, int b) {\n" +
            "        return a-b;\n" +
            "    }\n" +
            "}\n";

    public static void main(String[] args) throws Exception {

        Strategy strategy;

        strategy = getStrategy(Type.Adding);
        System.out.println(strategy.compute(10,20));

        strategy = getStrategy(Type.Substracting);
        System.out.println(strategy.compute(10,20));

    }

    public interface Strategy{
        int compute(int a, int b);
    }

    public static Strategy getStrategy(Type type) throws ClassNotFoundException, NoSuchMethodException, IllegalAccessException, InvocationTargetException, InstantiationException {
        {
            ClassLoader cl = new ClassLoader() {};
            CachedCompiler cc = new CachedCompiler(null, null);
            String strategyType = (type == Type.Adding) ? addingStrategy : subtractingStrategy;
            Class aClass = cc.loadFromJava(cl, className, strategyType);
            return (Strategy) aClass.getDeclaredConstructor().newInstance();
        }
    }

    public static class StrategyProxy implements Strategy{
        private volatile Strategy underlying;

        public void setStratgey(Strategy underlying){
            this.underlying = underlying;
        }

        public int compute(int a, int b){
            Strategy underlying = this.underlying;
            return underlying == null ? Integer.MIN_VALUE : underlying.compute(a, b);
        }
    }
}`

**Comment by dpisklov** [comment]
We don't plan to support intermediate (non-LTS) JDK releases. We support JDK 8, JDK 11 and the next one we will support is JDK 17 (TBC).
That said you're welcome to provide a PR.

**Comment by polarene** [comment]
@saulpalv you have a typo in the issue description:

> but crashes on JDK _**11**_

**Comment by radai-rosenblatt** [comment]
@dpisklov - the offending code (COmpilerUtils.java line ~ 60) could be turned into:
```java
DEFINE_CLASS_METHOD.setAccessible(true);
```
instead of using Unsafe to set the override flag to true.
i've tried it locally and it resolves this particular issue.

i bet there's a reason this wasnt done originally though that i'm missing?

**Comment by dpisklov** [comment]
@radai-rosenblatt `#setAccessible()` call produces loads of warnings on Java 9+ (and IIRC it doesn't even work on certain packages unless you specify some flags, don't remember exact details now), so we opted for unsafe access instead.

**Comment by JerryShea** [comment]
@saulpalv I believe this should work now. Have you had the chance to try again?

I am going to close - please reopen if you are still seeing this problem
