### ISSUE TITLE
Warnings regarding illegal reflective access operations

### ISSUE THREAD

**Issue by BryanWang1** [OpenHFT/Java-Runtime-Compiler#63]
Hi all, I'm getting an issue when trying to create a Chronicle Map or Queue of this sort.

"WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access using Lookup on net.openhft.chronicle.core.Jvm (file:/C:/Users/bryan/.m2/repository/net/openhft/chronicle-core/2.21ea61/chronicle-core-2.21ea61.jar) to class java.lang.reflect.AccessibleObject
WARNING: Please consider reporting this to the maintainers of net.openhft.chronicle.core.Jvm
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release"

I believe i'm on JDK 12 and I have this included in my pom.xml:
"     
  <dependency>
            <groupId>net.openhft</groupId>
            <artifactId>chronicle-map</artifactId>
            <version>3.21ea62</version>
            <type>bundle</type>
   </dependency>
"

I know many other developers are having this issue as shown here: https://github.com/OpenHFT/Chronicle-Map/issues/271

Any help would be greatly appreciated.

**Comment by RobAustin** [comment]
This is to be expected ( and will likely be like this till we produce the java 17 version ) currently it is written using Java 8 which is why you see these warnings.
