### ISSUE TITLE
Packages fail to import

### ISSUE THREAD

**Issue by ozanaaslan** [OpenHFT/Java-Runtime-Compiler#71]
Okay, so. 
i've tried to load code, which contains imports from packages, which aren't contained in java by default.
So API imports.

I get this error:
[15:37:25 WARN]: SLF4J: No SLF4J providers were found.
[15:37:25 WARN]: SLF4J: Defaulting to no-operation (NOP) logger implementation
[15:37:25 WARN]: SLF4J: See http://www.slf4j.org/codes.html#noProviders for further details.
[15:37:26 WARN]: /de/mcsilentde/game/oneinthechamber/utils/PlayerFetcher.java:15: error: package org.json does not exist
    public static org.json.JSONObject getPlayerJson(UUID uuid, String name) {
                          ^
/de/mcsilentde/game/oneinthechamber/utils/PlayerFetcher.java:14: error: package lombok does not exist
    @lombok.SneakyThrows
           ^

even though all of these packages mentioned are existing.
Please help

**Comment by JerryShea** [comment]
@SebyPlays can you provide a unit test which shows the problem?

**Comment by moritzvieli** [comment]
Had the same error when my classpath pointed to wrong directories:
CompilerUtils.addClassPath...

**Comment by JerryShea** [comment]
Good advice @moritzvieli

See also https://github.com/OpenHFT/Chronicle-Wire#spring-boots-and-dynamic-compilation-in-chronicle-wire

I am going to close this as no response received, but if you (@SebyPlays) can help us reproduce then we can reopen
