### ISSUE TITLE
Unclear README

### ISSUE THREAD

**Issue by uPaymeiFixit** [OpenHFT/Java-Runtime-Compiler#8]
The README for this project does not explain how to properly take advantage of this project. It looks great, but I'm not sure where to start. It looks like there is a working example included, but I don't see how to use it. 

Do you have any example code you could put on the README to show users how to utilize the CachedCompiler class?

**Comment by peter-lawrey** [comment]
I have updated the documentation a little. It should be clearer as to when it's a good idea to set this.

Your user name has a little irony ;)
