### ISSUE TITLE
package does not exist

### ISSUE THREAD

**Issue by aron-bordin** [OpenHFT/Java-Runtime-Compiler#9]
I'm trying to run the compiler inside a REST server, with Maven, but the compiler is not finding my .jar libraries.

mysource.java:3: error: package com.gargoylesoftware.htmlunit does not exist
import com.gargoylesoftware.htmlunit.BrowserVersion;
                                    ^
mysource.java:4: error: package com.gargoylesoftware.htmlunit does not exist
import com.gargoylesoftware.htmlunit.WebClient;
                                    ^
mysource.java:5: error: package com.gargoylesoftware.htmlunit.html does not exist
import com.gargoylesoftware.htmlunit.html.DomElement;

Is it possible to handle this situation? 

Thx

**Comment by peter-lawrey** [comment]
Are you using maven to run a Rest server? The api is design to be used at
run time rather than part of the build process.
I wouldn't use it in maven as it dies so special things to the class path
making it hard to find classes.
I would use it in your program after it is built once it is running.

Regards, Peter.

**Comment by aron-bordin** [comment]
I'm using the tomcat7 maven plugin to develop, and managing the project dependencies with Maven. 
I'm working with an Angular web application, where you can drag blocks to create an Java application. This webapp communicates a Java REST, and parses these blocks to a Java class. Then I was trying to use this lib to build this string.

My first approach was: http://stackoverflow.com/questions/935175/convert-string-to-code/30038318?noredirect=1#comment52789712_30038318
and then he guided me to this library. 
I'll try it again tomorrow

**Comment by peter-lawrey** [comment]
The library looks for classes in the class path of the provided
classloader. If you have multiple classloader you may need to use the one
which can see the classes you wish to compile against.

**Comment by aron-bordin** [comment]
I needed an compiler integrated with my system, so I reimplemented it.

Thx for the support :)

**Comment by st52572** [comment]
@aron-bordin I think I have kinda similiar problem to yours there. Can you tell me how did you use your integrated compiler or which one it is?
